config/routes.rb
Nobodyfuckthatguy::Application.routes.draw do
  devise_for :users

  resources :guys

   root :to => 'guys#index'

end

app/models/guy.rb
class Guy < ActiveRecord::Base
  attr_accessible :down_votes, :name, :story, :up_votes, :mug
  has_attached_file :mug
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/guys_controller.rb
class GuysController < ApplicationController
  # GET /guys
  # GET /guys.json
  def index
    @guys = Guy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @guys }
    end
  end

  # GET /guys/1
  # GET /guys/1.json
  def show
    @guy = Guy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @guy }
    end
  end

  # GET /guys/new
  # GET /guys/new.json
  def new
    @guy = Guy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @guy }
    end
  end

  # GET /guys/1/edit
  def edit
    @guy = Guy.find(params[:id])
  end

  # POST /guys
  # POST /guys.json
  def create
    @guy = Guy.new(params[:guy])

    respond_to do |format|
      if @guy.save
        format.html { redirect_to @guy, :notice => 'Guy was successfully created.' }
        format.json { render :json => @guy, :status => :created, :location => @guy }
      else
        format.html { render :action => "new" }
        format.json { render :json => @guy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /guys/1
  # PUT /guys/1.json
  def update
    @guy = Guy.find(params[:id])

    respond_to do |format|
      if @guy.update_attributes(params[:guy])
        format.html { redirect_to @guy, :notice => 'Guy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @guy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /guys/1
  # DELETE /guys/1.json
  def destroy
    @guy = Guy.find(params[:id])
    @guy.destroy

    respond_to do |format|
      format.html { redirect_to guys_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/guys_helper.rb
module GuysHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/guys/_form.html.erb
<%= form_for(@guy, :html => { :multipart => true }) do |f| %>
  <% if @guy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guy.errors.count, "error") %> prohibited this guy from being saved:</h2>

      <ul>
      <% @guy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :story %><br />
    <%= f.text_area :story %>
  </div>
  <div class="field">
    <%= f.label :mug %><br />
    <%= f.file_field :mug %>
  </div>
  <div class="field">
    <%= f.label :up_votes %><br />
    <%= f.number_field :up_votes %>
  </div>
  <div class="field">
    <%= f.label :down_votes %><br />
    <%= f.number_field :down_votes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guys/edit.html.erb
<h1>Editing guy</h1>

<%= render 'form' %>

<%= link_to 'Show', @guy %> |
<%= link_to 'Back', guys_path %>

app/views/guys/index.html.erb
<h1>Listing guys</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Story</th>
    <th>Up votes</th>
    <th>Down votes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guys.each do |guy| %>
  <tr>
    <td><%= guy.name %></td>
    <td><%= guy.story %></td>
    <td><%= guy.up_votes %></td>
    <td><%= guy.down_votes %></td>
    <td><%= link_to 'Show', guy %></td>
    <td><%= link_to 'Edit', edit_guy_path(guy) %></td>
    <td><%= link_to 'Destroy', guy, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guy', new_guy_path %>

app/views/guys/new.html.erb
<h1>New guy</h1>

<%= render 'form' %>

<%= link_to 'Back', guys_path %>

app/views/guys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @guy.name %>
</p>

<p>
  <b>Story:</b>
  <%= @guy.story %>
</p>

<p>
  <b>Up votes:</b>
  <%= @guy.up_votes %>
</p>

<p>
  <b>Down votes:</b>
  <%= @guy.down_votes %>
</p>
<p>
  <b>Image:</b>
  <%= image_tag @guy.mug.url %>
</p>

<%= link_to 'Edit', edit_guy_path(@guy) %> |
<%= link_to 'Back', guys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : APP_CONFIG[:site_title] %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>